### ISSUE TITLE
Populate network range property value in generated my-env-vars.yml

### ISSUE THREAD

**Issue by dmutreja** [oracle/terraform-oci-cf-install#6]
my-env-vars.yml placed in bastion is used with the bosh-deployment cloud-config to deploy cloudfoundry and other releases.  

cloud-config.yml contains manual network definition with 3 subnets which refers to variables <network_name>_range.  

Enhance templates to generate values for these these variables in my-env-bars.yml

**Comment by dmutreja** [comment]
Cloud-config contains 
```
networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr_n1))
    gateway: ((internal_gw_n1))
    az: z1
    dns: [8.8.8.8]
    static [((subnet1_static_ip_range))]
    cloud_properties:
      vcn: ((vcn))
      subnet_name: ((subnet1))
  - range: ((internal_cidr_n2))
    gateway: ((internal_gw_n2))
    az: z2
    dns: [8.8.8.8]
    static [((subnet2_static_ip_range))]
    cloud_properties:
      vcn: ((vcn))
      subnet_name: ((subnet2))

  - range: ((internal_cidr_n3))
    gateway: ((internal_gw_n3))
    az: z3
    dns: [8.8.8.8]
    static [((subnet3_static_ip_range))]
    cloud_properties:
      vcn: ((vcn))
      subnet_name: ((subnet3))

```

So generate the values for subnet1_static_ip_range, subnet2_static_ip_range, and subnet3_static_ip_range
